### ISSUE TITLE
Doesn't work with Grav 1.7 RC17

### ISSUE THREAD

**Issue by 01Kuzma** [matt-j-m/grav-plugin-aura#10]
It doesn't generate media in Grav 1.7 RC17
I hope it will be fixed soon

**Comment by TheRealThor** [comment]
Starting in Grav 1.7 the Event dispatcher is different and Grav uses different classes now, namely "PageObject" instead of "Page".  Line 80 of aura.php expect a Page object but gets a PagesObject object instead, so the function is returning doing nothing.

**Comment by matt-j-m** [comment]
Closing this issue as duplicate of #9
