### ISSUE TITLE
Can't update plugin with Grav 1.7 RC20

### ISSUE THREAD

**Issue by 01Kuzma** [matt-j-m/grav-plugin-aura#11]
Hi!
Little bug:
Can't update plugin from admin panel. Gettin this error:

> One of the packages require Grav >=1.7.0. Please update Grav to the latest release.

**Comment by danjames68** [comment]
Yes, me too.

**Comment by njadid** [comment]
Same here

**Comment by Karmalakas** [comment]
Same when trying to install

**Comment by matt-j-m** [comment]
Hopefully everyone is now on a stable release of >= Grav v1.7.0. The plugin updated and is working for me on Grav v1.7.3.
