### ISSUE TITLE
Latin extended character encoded

### ISSUE THREAD

**Issue by 01Kuzma** [matt-j-m/grav-plugin-aura#12]
Hi,
Found a bug:
The description uses Latin extended characters: "Senų baldų i&scaron;vežimo ..."
The character "Š" is encoded into html entity " & scaron;"

**Comment by Karmalakas** [comment]
Looking at source, `š` is encoded as `&amp;amp;scaron;` on my page :/
Also `'` is encoded as `&amp;#039;`

Grav v1.7.5
Admin v1.10.3
Aura v2.1.1

**Comment by Karmalakas** [comment]
@01Kuzma, check [my PR](https://github.com/matt-j-m/grav-plugin-aura/pull/19) and copy two aura.php files to your plugin. You'll have to re-save pages you need though. Hopefully this will get merged and will be able to update plugin as usual.

**Comment by 01Kuzma** [comment]
@Karmalakas thank you for PR, I will patch my files and try

**Comment by Karmalakas** [comment]
Note, that this also changes how `og:image` URL is retrieved. Check this too ;)

**Comment by 01Kuzma** [comment]
I've checked it (have overwritten `aura.php` and `classes/aura.php`)

In `og:image` now the root of web project is added twice, for example:
`https://localhost/transportopaslaugos/transportopaslaugos/user/pages/01.home/pervezimas.jpg`

By the way, it's really strange, but before pulling the changes I haven't observed an old error with `š` encoding. Maybe it also was related to Grav Core? Now it's updated to `1.7.7` and description is displayed without issues...

**Comment by Karmalakas** [comment]
> By the way, it's really strange, but before pulling the changes I haven't observed an old error with `š` encoding. Maybe it also was related to Grav Core? Now it's updated to `1.7.7` and description is displayed without issues...

Do you mean without my fix it's OK now? Because I'm on 1.7.7 and it's double encoded without the fix. I don't see a reason why Aura would do `htmlentites()` at all, when Grav 1.7 escapes already what's needed and plugin works only with 1.7

**Comment by 01Kuzma** [comment]
Yes, without fix it was OK (I've just observed it today), now I've applied the fix too on localhost firslty. That's very strange, since that time, when I've described this issue I was just updating Grav and wasn't looking at a description characters... So, I can't tell when the changes happened on my projects.
But as you still encounter the same problem - your's fix is mandatory for Aura :)
