### ISSUE TITLE
With set multilanguage doesn't work

### ISSUE THREAD

**Issue by 01Kuzma** [matt-j-m/grav-plugin-aura#13]
It seems that with multi language and Grav 1.7 plug-in doesn't work.
Only once switched to default language meta data is rendered, while switching to secondary language meta tags renders: " . . . "

**Comment by Karmalakas** [comment]
Did you save a page in second language? I have no issue there (both LT and EN are rendered)

**Comment by 01Kuzma** [comment]
@Karmalakas, that's strange, on one website everything works fine, on other the secondary language doesn't render description and keyword tags... Probably I should debug deeper

**Comment by Karmalakas** [comment]
Check how page frontmatter looks like. Default metadata template (unless you use custom) takes everything from `page.metadata`, which is saved in frontmatter as:
```yml
metadata:
  'og:description': 'Description'
```

**Comment by 01Kuzma** [comment]
Thank you!
On `localhost` it works, while on production - it's struggles. Probably there is a typo somewhere on a production version :/

**Comment by 01Kuzma** [comment]
My bad, it was a conflict with other plug-in

**Comment by Karmalakas** [comment]
You use two plugins for metadata? Which other one?

**Comment by 01Kuzma** [comment]
It was `grav-plugin-seo` I used it in past to change some data, so there was a conflict between them. I just've deleted it
