### ISSUE TITLE
Aura Will Not Update or Install

### ISSUE THREAD

**Issue by oldmanumby** [matt-j-m/grav-plugin-aura#14]
When I tried to update Aura, I got a warning saying I must update to GRAV 1.7 ... I did that, yet still get the warning. I then removed the plugin and tried reinstalling it, but now it won't install; same error message.

Suggestions?

**Comment by matt-j-m** [comment]
Hi @Umbyology I believe there was a larger issue with Grav not treating Grav v1.7 RC as >=  Grav v1.7. If you update to a stable release of Grav v1.7 I believe your issue will be solved. Cheers.
