### ISSUE TITLE
Twitter tags do not seem to be added to pages?

### ISSUE THREAD

**Issue by paulhibbitts** [matt-j-m/grav-plugin-aura#7]
Thanks very much for contributing this Plugin! I have installed/enabled the Plugin but it seems that the Twitter tags I was expecting to be added to pages are not appearing - perhaps I've done something wrong?

Here is a sample website page:  
https://opencoursehub.cs.sfu.ca/paulh/cmpt-363/202/schedule

BTW, I've manually added metadata to one of the site's pages and that is still working:  
https://opencoursehub.cs.sfu.ca/paulh/cmpt-363/202/home

Thanks very much,  
Paul

**Comment by matt-j-m** [comment]
Hi Paul have you recently updated to v2.0.0? There is a fundamental change to the plugin which will unfortunately break the way it worked previously. You don't need to re-enter anything, but you will need to actively re-save each page via the page editor.

If this is a new installation however, just double check your settings - under Output Settings you will need Twitter Card enabled, and a Twitter Username entered under Organization Information.

Let me know how you go.

Cheers

**Comment by paulhibbitts** [comment]
Hi @matt-j-m , thanks for quickly getting back to me. I did a fresh install with 2.0 but no Admin Panel save as I push all my changes via Git Sync  - do pages need to be saved in the Admin for the Plugin to work? If so, my workflow would not be suitable for using your Plugin (if I understand correctly🙂)

**Comment by matt-j-m** [comment]
Ah ok. Yes it does rely on the Admin plugin for meta data generation, so unfortunately won't work with your current workflow.

**Comment by paulhibbitts** [comment]
Ok, no problem - I will keep this Plugin in mind for other workflow scenarios. Thanks again for the clarification!
