### ISSUE TITLE
Page specific description not removed when saved

### ISSUE THREAD

**Issue by mahish** [matt-j-m/grav-plugin-aura#8]
Im having issue that the `.md` file is not updated when I delete page specific description. On top of that, additional metadata item is generated. [Please see this video](https://gyazo.com/cbfb7b5727344f2f139167737a0c4c09)

Using Grav 1.6 with up-to-date Admin plugin. I add Aura blueprint manually.

**Comment by matt-j-m** [comment]
Hi @mahish I believe this issue is now resolved with the latest plugin release v2.0.2. Please let me know if you are still experiencing an issue. Cheers.
