### ISSUE TITLE
metadata not being generated in Grav 1.7

### ISSUE THREAD

**Issue by danjames68** [matt-j-m/grav-plugin-aura#9]
I have Aura on a website running on Grav 1.16 and it does a stellar job. I have just added it to a new website running on 1.17 and the metadata isn't appearing in the source code. I've checked that 

```{% include 'partials/metadata.html.twig' %}```

is included, and it's present in both `base.html.twig` partials. Not sure what else to check. The two urls I've been checking against are:

https://invitationtotuscany.com/guide/coronavirus-travel-update-for-tuscany-italy

and

https://www.danwrightson.com/art/beetles-gallery

**Comment by matt-j-m** [comment]
Thanks for logging this, it is due to the change in Grav 1.7 to flex pages. I have logged with Grav here https://github.com/getgrav/grav/issues/3098

**Comment by danjames68** [comment]
Thanks Matt.

**Comment by matt-j-m** [comment]
Hi @danjames68 @01Kuzma the unimplemented `PageObject::getOriginal()` call has been fixed https://github.com/getgrav/grav/commit/6a0caebe2ee872ae98a582e29fd437c7ef4b7b79 and should be available in the next Grav 1.7 release. I will create a proper release of Aura 2.1.0 at that time so they will both work together.

If you need Aura working before that, you can manually apply that fix for Grav and then download and install Aura from the develop branch of this repo and it should function as normal.

**Comment by danjames68** [comment]
Brilliant, thanks Matt.

Best,

Dan

**Comment by 01Kuzma** [comment]
Great, thank you!
